{{- if (or .Values.externalWorkloads.enabled (not (eq .Values.cluster.name "default"))) }}
apiVersion: v1
kind: Service
metadata:
  name: "clustermesh-apiserver"
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: clustermesh-apiserver
  {{- with .Values.serviceAccounts.clustermeshApiserver.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
spec:
  type: {{ .Values.clustermesh.apiserver.service.type }}
  selector:
    k8s-app: clustermesh-apiserver
  ports:
  - port: 2379
{{- if and (eq "NodePort" .Values.clustermesh.apiserver.service.type) .Values.clustermesh.apiserver.service.nodePort }}
    nodePort: {{ .Values.clustermesh.apiserver.service.nodePort }}
{{- end }}
{{- if and (eq "LoadBalancer" .Values.clustermesh.apiserver.service.type) .Values.clustermesh.apiserver.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.clustermesh.apiserver.service.loadBalancerIP }}
{{- end }}
{{- end }}
