{{- if and (or .Values.externalWorkloads.enabled (not (eq .Values.cluster.name "default"))) .Values.clustermesh.apiserver.tls.auto.enabled (eq .Values.clustermesh.apiserver.tls.auto.method "cronJob") .Values.serviceAccounts.certgen.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustermesh-apiserver-generate-certs
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccounts.certgen.annotations }}
  annotations:
{{ toYaml .Values.serviceAccounts.certgen.annotations | indent 4 }}
{{- end }}
{{- end }}
